import mongoose, { Schema } from "mongoose";

const bookingSchema = new Schema(
    {
        user: {
            type: Schema.Types.ObjectId,
            ref: "User",
            required: true
        },
        // //feedback is give by user to expert
        feedback: {
            type: Schema.Types.ObjectId,
            ref: "Feedback",
        },
        expert: {
            type: Schema.Types.ObjectId,
            ref: "Expert",
            required: true,   
        },
        //report is generated by expert based on user performance
        report: {
            type: Schema.Types.ObjectId,
            ref: "Report",
        },
        appointmentDateTime: {
            type: String,
            required: true
        },
        bookedAt: {
            type: String,
            required: true
        },
        noteToExpert: {
            type: String
        },
        status: {
            type: String,
            enum: ["pending", "completed", "cancelled"],
            default: "pending"
        }
    },
    {
        timestamps: true
    }
);

export const Booking = mongoose.model('Booking', bookingSchema);
